#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Clinica")]
	public partial class DataClassesClinicaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertPaciente(Paciente instance);
    partial void UpdatePaciente(Paciente instance);
    partial void DeletePaciente(Paciente instance);
    partial void InsertHHCC(HHCC instance);
    partial void UpdateHHCC(HHCC instance);
    partial void DeleteHHCC(HHCC instance);
    partial void InsertActoMedico(ActoMedico instance);
    partial void UpdateActoMedico(ActoMedico instance);
    partial void DeleteActoMedico(ActoMedico instance);
    #endregion
		
		public DataClassesClinicaDataContext() : 
				base(global::CapaPresentacion.Properties.Settings.Default.DB_ClinicaConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesClinicaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesClinicaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesClinicaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesClinicaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Paciente> Paciente
		{
			get
			{
				return this.GetTable<Paciente>();
			}
		}
		
		public System.Data.Linq.Table<HHCC> HHCC
		{
			get
			{
				return this.GetTable<HHCC>();
			}
		}
		
		public System.Data.Linq.Table<ActoMedico> ActoMedico
		{
			get
			{
				return this.GetTable<ActoMedico>();
			}
		}
		
		public System.Data.Linq.Table<ActoMedicoDetalle> ActoMedicoDetalle
		{
			get
			{
				return this.GetTable<ActoMedicoDetalle>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paciente")]
	public partial class Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PacienteCodigo;
		
		private string _PacienteNombre;
		
		private string _PacienteApellido;
		
		private string _PacienteDireccion;
		
		private System.Nullable<int> _PacienteTelefono;
		
		private System.Nullable<System.DateTime> _PacienteNacimiento;
		
		private System.Nullable<byte> _EECCCodigo;
		
		private System.Nullable<byte> _GeneroCCodigo;
		
		private EntitySet<HHCC> _HHCC;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPacienteCodigoChanging(string value);
    partial void OnPacienteCodigoChanged();
    partial void OnPacienteNombreChanging(string value);
    partial void OnPacienteNombreChanged();
    partial void OnPacienteApellidoChanging(string value);
    partial void OnPacienteApellidoChanged();
    partial void OnPacienteDireccionChanging(string value);
    partial void OnPacienteDireccionChanged();
    partial void OnPacienteTelefonoChanging(System.Nullable<int> value);
    partial void OnPacienteTelefonoChanged();
    partial void OnPacienteNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnPacienteNacimientoChanged();
    partial void OnEECCCodigoChanging(System.Nullable<byte> value);
    partial void OnEECCCodigoChanged();
    partial void OnGeneroCCodigoChanging(System.Nullable<byte> value);
    partial void OnGeneroCCodigoChanged();
    #endregion
		
		public Paciente()
		{
			this._HHCC = new EntitySet<HHCC>(new Action<HHCC>(this.attach_HHCC), new Action<HHCC>(this.detach_HHCC));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteCodigo", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PacienteCodigo
		{
			get
			{
				return this._PacienteCodigo;
			}
			set
			{
				if ((this._PacienteCodigo != value))
				{
					this.OnPacienteCodigoChanging(value);
					this.SendPropertyChanging();
					this._PacienteCodigo = value;
					this.SendPropertyChanged("PacienteCodigo");
					this.OnPacienteCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteNombre", DbType="VarChar(30)")]
		public string PacienteNombre
		{
			get
			{
				return this._PacienteNombre;
			}
			set
			{
				if ((this._PacienteNombre != value))
				{
					this.OnPacienteNombreChanging(value);
					this.SendPropertyChanging();
					this._PacienteNombre = value;
					this.SendPropertyChanged("PacienteNombre");
					this.OnPacienteNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteApellido", DbType="VarChar(50)")]
		public string PacienteApellido
		{
			get
			{
				return this._PacienteApellido;
			}
			set
			{
				if ((this._PacienteApellido != value))
				{
					this.OnPacienteApellidoChanging(value);
					this.SendPropertyChanging();
					this._PacienteApellido = value;
					this.SendPropertyChanged("PacienteApellido");
					this.OnPacienteApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteDireccion", DbType="VarChar(150)")]
		public string PacienteDireccion
		{
			get
			{
				return this._PacienteDireccion;
			}
			set
			{
				if ((this._PacienteDireccion != value))
				{
					this.OnPacienteDireccionChanging(value);
					this.SendPropertyChanging();
					this._PacienteDireccion = value;
					this.SendPropertyChanged("PacienteDireccion");
					this.OnPacienteDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteTelefono", DbType="Int")]
		public System.Nullable<int> PacienteTelefono
		{
			get
			{
				return this._PacienteTelefono;
			}
			set
			{
				if ((this._PacienteTelefono != value))
				{
					this.OnPacienteTelefonoChanging(value);
					this.SendPropertyChanging();
					this._PacienteTelefono = value;
					this.SendPropertyChanged("PacienteTelefono");
					this.OnPacienteTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> PacienteNacimiento
		{
			get
			{
				return this._PacienteNacimiento;
			}
			set
			{
				if ((this._PacienteNacimiento != value))
				{
					this.OnPacienteNacimientoChanging(value);
					this.SendPropertyChanging();
					this._PacienteNacimiento = value;
					this.SendPropertyChanged("PacienteNacimiento");
					this.OnPacienteNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EECCCodigo", DbType="TinyInt")]
		public System.Nullable<byte> EECCCodigo
		{
			get
			{
				return this._EECCCodigo;
			}
			set
			{
				if ((this._EECCCodigo != value))
				{
					this.OnEECCCodigoChanging(value);
					this.SendPropertyChanging();
					this._EECCCodigo = value;
					this.SendPropertyChanged("EECCCodigo");
					this.OnEECCCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeneroCCodigo", DbType="TinyInt")]
		public System.Nullable<byte> GeneroCCodigo
		{
			get
			{
				return this._GeneroCCodigo;
			}
			set
			{
				if ((this._GeneroCCodigo != value))
				{
					this.OnGeneroCCodigoChanging(value);
					this.SendPropertyChanging();
					this._GeneroCCodigo = value;
					this.SendPropertyChanged("GeneroCCodigo");
					this.OnGeneroCCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_HHCC", Storage="_HHCC", ThisKey="PacienteCodigo", OtherKey="PacienteCodigo")]
		public EntitySet<HHCC> HHCC
		{
			get
			{
				return this._HHCC;
			}
			set
			{
				this._HHCC.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HHCC(HHCC entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = this;
		}
		
		private void detach_HHCC(HHCC entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HHCC")]
	public partial class HHCC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HHCCCodigo;
		
		private System.Nullable<System.DateTime> _HHCCFecha;
		
		private string _PacienteCodigo;
		
		private EntitySet<ActoMedico> _ActoMedico;
		
		private EntityRef<Paciente> _Paciente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHHCCCodigoChanging(int value);
    partial void OnHHCCCodigoChanged();
    partial void OnHHCCFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnHHCCFechaChanged();
    partial void OnPacienteCodigoChanging(string value);
    partial void OnPacienteCodigoChanged();
    #endregion
		
		public HHCC()
		{
			this._ActoMedico = new EntitySet<ActoMedico>(new Action<ActoMedico>(this.attach_ActoMedico), new Action<ActoMedico>(this.detach_ActoMedico));
			this._Paciente = default(EntityRef<Paciente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HHCCCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HHCCCodigo
		{
			get
			{
				return this._HHCCCodigo;
			}
			set
			{
				if ((this._HHCCCodigo != value))
				{
					this.OnHHCCCodigoChanging(value);
					this.SendPropertyChanging();
					this._HHCCCodigo = value;
					this.SendPropertyChanged("HHCCCodigo");
					this.OnHHCCCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HHCCFecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> HHCCFecha
		{
			get
			{
				return this._HHCCFecha;
			}
			set
			{
				if ((this._HHCCFecha != value))
				{
					this.OnHHCCFechaChanging(value);
					this.SendPropertyChanging();
					this._HHCCFecha = value;
					this.SendPropertyChanged("HHCCFecha");
					this.OnHHCCFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteCodigo", DbType="VarChar(8)")]
		public string PacienteCodigo
		{
			get
			{
				return this._PacienteCodigo;
			}
			set
			{
				if ((this._PacienteCodigo != value))
				{
					if (this._Paciente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPacienteCodigoChanging(value);
					this.SendPropertyChanging();
					this._PacienteCodigo = value;
					this.SendPropertyChanged("PacienteCodigo");
					this.OnPacienteCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HHCC_ActoMedico", Storage="_ActoMedico", ThisKey="HHCCCodigo", OtherKey="HHCCCodigo")]
		public EntitySet<ActoMedico> ActoMedico
		{
			get
			{
				return this._ActoMedico;
			}
			set
			{
				this._ActoMedico.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_HHCC", Storage="_Paciente", ThisKey="PacienteCodigo", OtherKey="PacienteCodigo", IsForeignKey=true)]
		public Paciente Paciente
		{
			get
			{
				return this._Paciente.Entity;
			}
			set
			{
				Paciente previousValue = this._Paciente.Entity;
				if (((previousValue != value) 
							|| (this._Paciente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paciente.Entity = null;
						previousValue.HHCC.Remove(this);
					}
					this._Paciente.Entity = value;
					if ((value != null))
					{
						value.HHCC.Add(this);
						this._PacienteCodigo = value.PacienteCodigo;
					}
					else
					{
						this._PacienteCodigo = default(string);
					}
					this.SendPropertyChanged("Paciente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ActoMedico(ActoMedico entity)
		{
			this.SendPropertyChanging();
			entity.HHCC = this;
		}
		
		private void detach_ActoMedico(ActoMedico entity)
		{
			this.SendPropertyChanging();
			entity.HHCC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActoMedico")]
	public partial class ActoMedico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ActoMedicoCodigo;
		
		private System.Nullable<System.DateTime> _ActoMedicoFecha;
		
		private System.Nullable<int> _HHCCCodigo;
		
		private System.Nullable<int> _EspecialistaCMP;
		
		private string _ActoMedicoObservacion;
		
		private EntityRef<HHCC> _HHCC;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnActoMedicoCodigoChanging(int value);
    partial void OnActoMedicoCodigoChanged();
    partial void OnActoMedicoFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnActoMedicoFechaChanged();
    partial void OnHHCCCodigoChanging(System.Nullable<int> value);
    partial void OnHHCCCodigoChanged();
    partial void OnEspecialistaCMPChanging(System.Nullable<int> value);
    partial void OnEspecialistaCMPChanged();
    partial void OnActoMedicoObservacionChanging(string value);
    partial void OnActoMedicoObservacionChanged();
    #endregion
		
		public ActoMedico()
		{
			this._HHCC = default(EntityRef<HHCC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActoMedicoCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ActoMedicoCodigo
		{
			get
			{
				return this._ActoMedicoCodigo;
			}
			set
			{
				if ((this._ActoMedicoCodigo != value))
				{
					this.OnActoMedicoCodigoChanging(value);
					this.SendPropertyChanging();
					this._ActoMedicoCodigo = value;
					this.SendPropertyChanged("ActoMedicoCodigo");
					this.OnActoMedicoCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActoMedicoFecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActoMedicoFecha
		{
			get
			{
				return this._ActoMedicoFecha;
			}
			set
			{
				if ((this._ActoMedicoFecha != value))
				{
					this.OnActoMedicoFechaChanging(value);
					this.SendPropertyChanging();
					this._ActoMedicoFecha = value;
					this.SendPropertyChanged("ActoMedicoFecha");
					this.OnActoMedicoFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HHCCCodigo", DbType="Int")]
		public System.Nullable<int> HHCCCodigo
		{
			get
			{
				return this._HHCCCodigo;
			}
			set
			{
				if ((this._HHCCCodigo != value))
				{
					if (this._HHCC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHHCCCodigoChanging(value);
					this.SendPropertyChanging();
					this._HHCCCodigo = value;
					this.SendPropertyChanged("HHCCCodigo");
					this.OnHHCCCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EspecialistaCMP", DbType="Int")]
		public System.Nullable<int> EspecialistaCMP
		{
			get
			{
				return this._EspecialistaCMP;
			}
			set
			{
				if ((this._EspecialistaCMP != value))
				{
					this.OnEspecialistaCMPChanging(value);
					this.SendPropertyChanging();
					this._EspecialistaCMP = value;
					this.SendPropertyChanged("EspecialistaCMP");
					this.OnEspecialistaCMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActoMedicoObservacion", DbType="VarChar(250)")]
		public string ActoMedicoObservacion
		{
			get
			{
				return this._ActoMedicoObservacion;
			}
			set
			{
				if ((this._ActoMedicoObservacion != value))
				{
					this.OnActoMedicoObservacionChanging(value);
					this.SendPropertyChanging();
					this._ActoMedicoObservacion = value;
					this.SendPropertyChanged("ActoMedicoObservacion");
					this.OnActoMedicoObservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HHCC_ActoMedico", Storage="_HHCC", ThisKey="HHCCCodigo", OtherKey="HHCCCodigo", IsForeignKey=true)]
		public HHCC HHCC
		{
			get
			{
				return this._HHCC.Entity;
			}
			set
			{
				HHCC previousValue = this._HHCC.Entity;
				if (((previousValue != value) 
							|| (this._HHCC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HHCC.Entity = null;
						previousValue.ActoMedico.Remove(this);
					}
					this._HHCC.Entity = value;
					if ((value != null))
					{
						value.ActoMedico.Add(this);
						this._HHCCCodigo = value.HHCCCodigo;
					}
					else
					{
						this._HHCCCodigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("HHCC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActoMedicoDetalle")]
	public partial class ActoMedicoDetalle
	{
		
		private System.Nullable<int> _ActoMedicoCodigo;
		
		private System.Nullable<double> _fiebre;
		
		private System.Nullable<bool> _tos;
		
		private System.Nullable<bool> _dolorCabeza;
		
		private System.Nullable<bool> _dolorMusculares;
		
		private System.Nullable<bool> _malestarGeneral;
		
		private System.Nullable<bool> _dolorGarganta;
		
		private System.Nullable<bool> _secreciónNasal;
		
		public ActoMedicoDetalle()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActoMedicoCodigo", DbType="Int")]
		public System.Nullable<int> ActoMedicoCodigo
		{
			get
			{
				return this._ActoMedicoCodigo;
			}
			set
			{
				if ((this._ActoMedicoCodigo != value))
				{
					this._ActoMedicoCodigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiebre", DbType="Float")]
		public System.Nullable<double> fiebre
		{
			get
			{
				return this._fiebre;
			}
			set
			{
				if ((this._fiebre != value))
				{
					this._fiebre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tos", DbType="Bit")]
		public System.Nullable<bool> tos
		{
			get
			{
				return this._tos;
			}
			set
			{
				if ((this._tos != value))
				{
					this._tos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dolorCabeza", DbType="Bit")]
		public System.Nullable<bool> dolorCabeza
		{
			get
			{
				return this._dolorCabeza;
			}
			set
			{
				if ((this._dolorCabeza != value))
				{
					this._dolorCabeza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dolorMusculares", DbType="Bit")]
		public System.Nullable<bool> dolorMusculares
		{
			get
			{
				return this._dolorMusculares;
			}
			set
			{
				if ((this._dolorMusculares != value))
				{
					this._dolorMusculares = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malestarGeneral", DbType="Bit")]
		public System.Nullable<bool> malestarGeneral
		{
			get
			{
				return this._malestarGeneral;
			}
			set
			{
				if ((this._malestarGeneral != value))
				{
					this._malestarGeneral = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dolorGarganta", DbType="Bit")]
		public System.Nullable<bool> dolorGarganta
		{
			get
			{
				return this._dolorGarganta;
			}
			set
			{
				if ((this._dolorGarganta != value))
				{
					this._dolorGarganta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secreciónNasal", DbType="Bit")]
		public System.Nullable<bool> secreciónNasal
		{
			get
			{
				return this._secreciónNasal;
			}
			set
			{
				if ((this._secreciónNasal != value))
				{
					this._secreciónNasal = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
